dist: xenial
language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy3.5-7.0.0"
    - "pypy3.6-7.1.1"
install:
    - pip install -r test-requirements.txt
script:
    # Only run mypy in "3.5" job, because installing it fails in PyPy jobs
    - |
      if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then
        pip install mypy &&
        mypy .
      fi
    - pytest --flake8 --cov=base58 .
after_success:
    coveralls
