language: python
sudo: false
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
install:
    - pip install -r test-requirements.txt
script:
    nosetests --with-coverage --cover-package=base58
after_success:
    coveralls
